name: Update birthday

on:
  push:
    branches:
     - master
  schedule:
    - cron: "0 0 21 2 *"
  workflow_dispatch:

jobs:
  update-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate age
        id: age
        run: |
          BIRTHDATE="2005-02-21"
          TODAY=$(date -u +"%Y-%m-%d")
          AGE=$(( $(date -u -d "$TODAY" +%Y) - $(date -u -d "$BIRTHDATE" +%Y) ))
          if [ "$(date -u -d "$TODAY" +%m%d)" -lt "$(date -u -d "$BIRTHDATE" +%m%d)" ]; then AGE=$((AGE-1)); fi
          echo "age=$AGE" >> "$GITHUB_OUTPUT"

      - name: Generate README.md from template
        run: |
          sed "s/{age}/${{ steps.age.outputs.age }}/g" README_TEMPLATE.md > README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: update README age to ${{ steps.age.outputs.age }}"
          git push